### ISSUE TITLE
Should bezier.lineIntersects(line) work for line-line intersections?

### ISSUE THREAD

**Issue by justvanrossum** [Pomax/bezierjs#200]
It currently doesn't for me, failing like this:

```
TypeError: Cannot read properties of undefined (reading 'y')
    at Object.roots (bezier-js.js:553:23)
    at Bezier.lineIntersects (bezier-js.js:1824:18)
```

I'm not immediately sure what's going on, but if the intention is for this to work, I'd be happy to try to contribute a fix.

**Comment by justvanrossum** [comment]
I don't have a strong opinion, I just noticed many things just work for lines, such as project, derivative, get/compute, so I was intuitively hoping it would do line intersection, too.
